BROWSER: "Chrome"
WIN_BROWSER: "chromedriver.exe"
MAC_BROWSER: "chromedriver"

WEBPAGE:
   URL: "http://localhost:8080/"
   SWAGGER_URL: "http://localhost:8080/swagger-ui.html"

PROCESS:
   GET_PID: "ps -eaf | grep -i OppenheimerProjectDev.jar | grep -v grep | head -1 | awk {'print $2'}"

REQUESTDATA:
   insert_single_1 : { "salary": "6000",
    "natid": "111-$$$$$$",
    "name": "ROBIN WILLIAMS",
    "gender": "M",
    "tax": "1000",
    "birthday": "12111999"
    }
   insert_single_2 : { "salary": "3900",
    "natid": "333-$$$$$",
    "name": "JADEN SMITH",
    "gender": "M",
    "tax": "250",
    "birthday": "12041988"
    }
   insert_single_3 : { "salary": "5000",
    "natid": "736-$$$$$$$",
    "name": "Stephany Prohaska",
    "gender": "F",
    "tax": "200",
    "birthday": "15041982"
    }
    
   insert_multiple: { "records" : [{ "birthday": 01101989, "gender": "MALE", "name": "ROBIN", "natid": "111-$$$$$$$", "salary": "true", "tax": "true" }, { "birthday": 05111991, "gender": "FEMALE", "name": "LUCY", "natid": "122-$$$$$$$", "salary": "true", "tax": "false" }, { "birthday": 09122000, "gender": "MALE", "name": "CHARLES", "natid": "132-$$$$$$$", "salary": "false", "tax": "true" }]}
   
   excel_datas: { "records" : [{ "birthday": 20062009, "gender": "F", "name": "Shiela John ", "natid": "777-$$$$$$$", "salary": "3000", "tax": "150" }, { "birthday": 11091985, "gender": "M", "name": "Charles Butwiski", "natid": "887-$$$$$$$", "salary": "4500", "tax": "220" }, { "birthday": 09122000, "gender": "M", "name": "Rahul Kumar", "natid": "332-$$$$$$$", "salary": "5000", "tax": "300" }]}